### ISSUE TITLE
rebase: support `--fork-point`

### ISSUE THREAD

**Issue by olets** [olets/git-replay#13]
Maybe by default?

Or maybe another top-level config, `rebase-fork-point`?

Or more generally some way to pass Git flags?

```yaml
rebase:
  branch-a:
    -
      branch: branch-b
      config: --fork-point
```
