### ISSUE TITLE
make "there is a problem in the … configuration" user-friendlier

### ISSUE THREAD

**Issue by olets** [olets/git-replay#7]
Currently an excerpt of the yq query is given, for example

```yaml
rebase:
  base:
    - feature # does not exist
```

```
There is a problem in the 'rebase."base".*' configuration.
````

Better would be

```
There is a problem in the 'rebase.base' configuration.
```
