### ISSUE TITLE
stage: require start point and branch

### ISSUE THREAD

**Issue by olets** [olets/git-replay#8]
Currently you can config

```yaml
stage:
  start-point:
    - my-branch
```

The result will be

```shell
% git replay
Resetting 0 to master
git checkout -B 0 master
Switched to a new branch '0'
Replay complete
% git branch --show-current 
0
```

Enforce the necessary depth. The above configuration should give an error (based on git-replay's existing error messages). Should have to be something like

```yaml
stage:
  start-point:
    branch: commit
```
